name: Test & Deploy FastAPI to Cloud Run

on:
  push:
    branches: [main,develop]

    workflow_dispatch:

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: cyberstage
      REGION: us-central1
      SERVICE: fastapi-app

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest app/tests/

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        install_components: docker

    - name: Auth Docker with GCR
      run: gcloud auth configure-docker --quiet

    - name: Build & Push Docker image from /app
      run: |
        docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest ./app
        docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE }} \
          --image gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:latest \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated
